### ISSUE TITLE
Phone app

### ISSUE THREAD

**Issue by danya02** [danya02/public-bodyguard#2]
We need an app that would work on phones: that would get info from the GPS module, notify the user of events, communicate with the server (#1), etc.

**Comment by Rudoff94** [comment]
Даня, привет,  я написал программу (button_test.py)  можешь проверить ее в
деле.

7 авг. 2016 г. 18:13 пользователь "Danya Generalov" <
notifications@github.com> написал:

**Comment by danya02** [comment]
> Даня, привет,  я написал программу (button_test.py)  можешь проверить ее в
> деле.

Мог бы, если бы знал, где хранится.

**Comment by Rudoff94** [comment]
Raspberry на столе в 400, программа в домашней директории

8 авг. 2016 г. 14:54 пользователь "Danya Generalov" <
notifications@github.com> написал:

**Comment by danya02** [comment]
ОК, проверю в ближайшее время.

**Comment by Rudoff94** [comment]
Отлично)

8 авг. 2016 г. 14:56 пользователь "Danya Generalov" <
notifications@github.com> написал:

**Comment by danya02** [comment]
Если честно, я даже не понимаю, как этот код работает. Понял только, что как-то не так. Вот [мой вариант](https://gist.github.com/danya02/06374d7290db76479a42c4c50d65a502).
