### ISSUE TITLE
Wristband

### ISSUE THREAD

**Issue by danya02** [danya02/public-bodyguard#3]
We need a device that would invoke the program for phones (#2), telling it to do actions by Bluetooth, via a button press.

**Comment by danya02** [comment]
@Rudoff94, are you going to do this? 'Cause, you know, the deadline is in less than 3 days and yet we don't even have the phone app #2 ready?..

**Comment by Rudoff94** [comment]
Дань, можно и по русски)  да, я попробую что-нибудь придумать

5 авг. 2016 г. 22:35 пользователь "Danya Generalov" <
notifications@github.com> написал:

**Comment by danya02** [comment]
Хорошо, просто хотелось бы закончить побыстрее.
P. S. 

> Дань, можно и по русски)

Да, по русски можно, но это гораздо (примерно в 4 раза) дольше печатать.
P. P. S. Я сделал чат на [Gitter](https://gitter.im/public-bodyguard/Lobby), общаться можно там.
